// Compress niche photos: jpg sources → webp + LQIP registry.
import sharp from 'sharp';
import { readdirSync, statSync, existsSync, writeFileSync, unlinkSync } from 'fs';
import { join } from 'path';

const ROOT = 'public/niche-covers';

const slugs = readdirSync(ROOT).filter(d => statSync(join(ROOT, d)).isDirectory());

const out = {};
let totalKB = 0;
for (const slug of slugs) {
  const dir = join(ROOT, slug);
  const jpgs = readdirSync(dir).filter(f => f.endsWith('.jpg')).sort();
  if (jpgs.length === 0) {
    // Already webp? Just rebuild LQIP from existing webp.
    const webps = readdirSync(dir).filter(f => f.endsWith('.webp')).sort();
    if (webps.length === 0) continue;
    const blur = [];
    for (const f of webps) {
      const buf = await sharp(join(dir, f)).resize(24, 24, { fit: 'cover' }).webp({ quality: 30 }).toBuffer();
      blur.push(`data:image/webp;base64,${buf.toString('base64')}`);
    }
    out[slug] = { count: webps.length, blur };
    continue;
  }
  const blur = [];
  for (let i = 0; i < jpgs.length; i++) {
    const src = join(dir, jpgs[i]);
    const dst = join(dir, `${i + 1}.webp`);
    const buf = await sharp(src).resize(640, 640, { fit: 'cover' }).webp({ quality: 62, effort: 6 }).toBuffer();
    await sharp(buf).toFile(dst);
    totalKB += buf.length / 1024;
    const b = await sharp(src).resize(24, 24, { fit: 'cover' }).webp({ quality: 30 }).toBuffer();
    blur.push(`data:image/webp;base64,${b.toString('base64')}`);
    unlinkSync(src);
  }
  out[slug] = { count: jpgs.length, blur };
}

const lines = ['// AUTO-GENERATED by scripts/compress-niches.mjs', 'import type { NicheCover } from "@/data/niche-covers";', '', 'export const COVERS: Record<string, NicheCover> = {'];
for (const slug of Object.keys(out).sort()) {
  const blurs = out[slug].blur.map(b => `"${b}"`).join(', ');
  lines.push(`  "${slug}": { count: ${out[slug].count}, blur: [${blurs}] },`);
}
lines.push('};', '');
writeFileSync('/tmp/niche-covers.ts', lines.join('\n'));
console.log(`Compressed ${slugs.length} niches. Total webp: ${Math.round(totalKB)} KB`);
console.log(`Snippet → /tmp/niche-covers.ts`);
