// Build mood-cover registry from public/mood-covers/{theme}/{i}.webp.
// Resizes to ~256px (circle thumbs are 32-64px tall) and emits LQIP blurs.
import sharp from 'sharp';
import { readdirSync, statSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = 'public/mood-covers';
const themes = readdirSync(ROOT).filter(d => statSync(join(ROOT, d)).isDirectory()).sort();

const out = {};
let totalKB = 0;
for (const theme of themes) {
  const dir = join(ROOT, theme);
  const webps = readdirSync(dir).filter(f => /^\d+\.webp$/.test(f)).sort();
  if (webps.length === 0) continue;
  const blur = [];
  for (const f of webps) {
    const src = join(dir, f);
    // Re-encode small + crisp circle thumb.
    const buf = await sharp(src).resize(256, 256, { fit: 'cover' }).webp({ quality: 70, effort: 6 }).toBuffer();
    writeFileSync(src, buf);
    totalKB += buf.length / 1024;
    const b = await sharp(src).resize(20, 20, { fit: 'cover' }).webp({ quality: 30 }).toBuffer();
    blur.push(`data:image/webp;base64,${b.toString('base64')}`);
  }
  out[theme] = { count: webps.length, blur };
}

const lines = [
  '// AUTO-GENERATED by scripts/compress-moods.mjs.',
  'export interface MoodCover { count: number; blur: string[] }',
  '',
  'export const MOOD_COVERS: Record<string, MoodCover> = {',
];
for (const theme of Object.keys(out).sort()) {
  const blurs = out[theme].blur.map(b => `"${b}"`).join(', ');
  lines.push(`  "${theme}": { count: ${out[theme].count}, blur: [${blurs}] },`);
}
lines.push(
  '};',
  '',
  'export const moodUrl = (theme: string, i: number): string =>',
  '  `/mood-covers/${theme}/${i + 1}.webp`;',
  '',
);
writeFileSync('src/data/mood-covers.ts', lines.join('\n'));
console.log(`Compressed ${themes.length} moods. Total webp: ${Math.round(totalKB)} KB`);
