// Process city cover folders. Picks up base {state}.jpg AND alternate {state}-2.jpg / {state}-3.jpg.
// Emits .webp (480x600) for each, plus LQIP for the base. Rewrites src/data/city-covers.ts in full.
import sharp from 'sharp';
import { readdirSync, statSync, existsSync, writeFileSync, unlinkSync } from 'fs';
import { join } from 'path';

const ROOT = 'public/city-covers';
const STATES = ['dawn', 'day', 'golden', 'night'];

const TZ = {
  'chapter-nyc': 'America/New_York',
  'chapter-la': 'America/Los_Angeles',
  'chapter-bay-area': 'America/Los_Angeles',
  'chapter-chicagoland': 'America/Chicago',
  'chapter-seattle': 'America/Los_Angeles',
  'chapter-miami': 'America/New_York',
  'london-chapter': 'Europe/London',
  'chapter-boston': 'America/New_York',
  'brooklyn-chapter': 'America/New_York',
  'chapter-dc': 'America/New_York',
  'chapter-toronto': 'America/Toronto',
  'chapter-paris': 'Europe/Paris',
  'chapter-sydney': 'Australia/Sydney',
  'chapter-austin': 'America/Chicago',
  'chapter-vancouver': 'America/Vancouver',
  'chapter-berlin': 'Europe/Berlin',
  'chapter-philly': 'America/New_York',
  'chapter-atlanta': 'America/New_York',
  'chapter-denver': 'America/Denver',
  'chapter-portland': 'America/Los_Angeles',
  'chapter-phoenix': 'America/Phoenix',
  'chapter-san-diego': 'America/Los_Angeles',
  'chapter-twin-cities': 'America/Chicago',
  'chapter-nashville': 'America/Chicago',
  'chapter-nola': 'America/Chicago',
  'chapter-detroit': 'America/Detroit',
  'chapter-houston': 'America/Chicago',
  'chapter-dfw': 'America/Chicago',
  'chapter-vegas': 'America/Los_Angeles',
  'chapter-montreal': 'America/Toronto',
  'chapter-amsterdam': 'Europe/Amsterdam',
  'chapter-dublin': 'Europe/Dublin',
  'chapter-tokyo': 'Asia/Tokyo',
  'chapter-singapore': 'Asia/Singapore',
  'chapter-melbourne': 'Australia/Melbourne',
  'chapter-cdmx': 'America/Mexico_City',
  'chapter-madrid': 'Europe/Madrid',
  'chapter-barcelona': 'Europe/Madrid',
  'chapter-manchester': 'Europe/London',
  'chapter-baltimore': 'America/New_York',
  'chapter-pittsburgh': 'America/New_York',
  'chapter-charlotte': 'America/New_York',
  'chapter-orlando': 'America/New_York',
  'chapter-san-jose': 'America/Los_Angeles',
};

const cities = readdirSync(ROOT).filter(d => statSync(join(ROOT, d)).isDirectory()).sort();

const out = {};
let totalKB = 0;
let processed = 0;

for (const c of cities) {
  const dir = join(ROOT, c);
  const blur = {};
  const count = {};
  let hasAny = false;

  for (const s of STATES) {
    // Convert any new {state}*.jpg → webp (skip existing webps).
    for (const variant of ['', '-2', '-3']) {
      const jpg = join(dir, `${s}${variant}.jpg`);
      const webp = join(dir, `${s}${variant}.webp`);
      if (existsSync(jpg)) {
        const buf = await sharp(jpg).resize(480, 600, { fit: 'cover' }).webp({ quality: 60, effort: 6 }).toBuffer();
        writeFileSync(webp, buf);
        totalKB += buf.length / 1024;
        unlinkSync(jpg);
        processed++;
      }
    }

    // Count available webp variants.
    let n = 0;
    for (const variant of ['', '-2', '-3']) {
      if (existsSync(join(dir, `${s}${variant}.webp`))) n++;
      else break;
    }
    if (n === 0) continue;
    hasAny = true;
    count[s] = n;

    // Generate / preserve LQIP from base photo.
    const base = join(dir, `${s}.webp`);
    const lqip = await sharp(base).resize(24, 30, { fit: 'cover' }).webp({ quality: 30 }).toBuffer();
    blur[s] = `data:image/webp;base64,${lqip.toString('base64')}`;
  }

  if (!hasAny) continue;
  out[c] = { tz: TZ[c] ?? 'UTC', blur, count };
}

// Emit full TS file.
const lines = [
  '// Auto-generated by scripts/compress-covers.mjs. Bright/optimistic city imagery.',
  'export type DayState = "dawn" | "day" | "golden" | "night";',
  '',
  'export interface CityCover {',
  '  tz: string;',
  '  blur: Record<DayState, string>;',
  '  /** Number of photos available per state (1 = base only; 2/3 = base + alternates). */',
  '  count?: Partial<Record<DayState, number>>;',
  '}',
  '',
  'export const CITY_COVERS: Record<string, CityCover> = {',
];
for (const c of Object.keys(out).sort()) {
  const { tz, blur, count } = out[c];
  const blurStr = STATES.filter(s => blur[s]).map(s => `${s}: "${blur[s]}"`).join(', ');
  const countStr = STATES.filter(s => (count[s] ?? 0) > 1).map(s => `${s}: ${count[s]}`).join(', ');
  const countPart = countStr ? `, count: { ${countStr} }` : '';
  lines.push(`  "${c}": { tz: "${tz}", blur: { ${blurStr} }${countPart} },`);
}
lines.push(
  '};',
  '',
  'export function dayStateFromHour(hour: number): DayState {',
  '  if (hour < 5 || hour >= 20) return "night";',
  '  if (hour < 7) return "dawn";',
  '  if (hour < 17) return "day";',
  '  if (hour < 19) return "golden";',
  '  return "night";',
  '}',
  '',
  'export function coverUrl(slug: string, state: DayState, idx = 0): string {',
  '  const suffix = idx === 0 ? "" : `-${idx + 1}`;',
  '  return `/city-covers/${slug}/${state}${suffix}.webp`;',
  '}',
  '',
);
writeFileSync('src/data/city-covers.ts', lines.join('\n'));
console.log(`Cities: ${Object.keys(out).length}. New conversions: ${processed}. Total webp bytes: ${Math.round(totalKB)} KB`);
