/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoreRouteImport } from './routes/more'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WCodeRouteImport } from './routes/w.$code'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ShopReturnRouteImport } from './routes/shop.return'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminRadioRouteImport } from './routes/admin.radio'
import { Route as AdminPodcastsRouteImport } from './routes/admin.podcasts'
import { Route as AdminMerchRouteImport } from './routes/admin.merch'
import { Route as AdminMembershipRouteImport } from './routes/admin.membership'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AuthenticatedTrailsRouteImport } from './routes/_authenticated/trails'
import { Route as AuthenticatedPlacesRouteImport } from './routes/_authenticated/places'
import { Route as AuthenticatedListenRouteImport } from './routes/_authenticated/listen'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedCirclesRouteImport } from './routes/_authenticated/circles'
import { Route as AuthenticatedWalkIndexRouteImport } from './routes/_authenticated/walk.index'
import { Route as WCodeRecapRouteImport } from './routes/w.$code.recap'
import { Route as AdminRadioIdRouteImport } from './routes/admin.radio.$id'
import { Route as AdminPodcastsFeedIdRouteImport } from './routes/admin.podcasts.$feedId'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AuthenticatedWalkNewRouteImport } from './routes/_authenticated/walk.new'
import { Route as AuthenticatedTrailsIdRouteImport } from './routes/_authenticated/trails.$id'
import { Route as AuthenticatedReadPostIdRouteImport } from './routes/_authenticated/read.$postId'
import { Route as AuthenticatedPlacesKeyRouteImport } from './routes/_authenticated/places.$key'
import { Route as AuthenticatedListenIdRouteImport } from './routes/_authenticated/listen.$id'
import { Route as AuthenticatedGroupsSlugRouteImport } from './routes/_authenticated/groups.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSyncPodcastFeedsRouteImport } from './routes/api/public/hooks/sync-podcast-feeds'
import { Route as ApiPublicHooksSyncBlogFeedsRouteImport } from './routes/api/public/hooks/sync-blog-feeds'
import { Route as AuthenticatedListenCollectionSlugRouteImport } from './routes/_authenticated/listen.collection.$slug'
import { Route as ApiPublicWalkCodeStoryRouteImport } from './routes/api/public/walk.$code.story'
import { Route as ApiPublicWalkCodeRsvpRouteImport } from './routes/api/public/walk.$code.rsvp'
import { Route as ApiPublicWalkCodeOgRouteImport } from './routes/api/public/walk.$code.og'
import { Route as ApiPublicWalkCodeIcsRouteImport } from './routes/api/public/walk.$code.ics'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WCodeRoute = WCodeRouteImport.update({
  id: '/w/$code',
  path: '/w/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopReturnRoute = ShopReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => ShopRoute,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRadioRoute = AdminRadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastsRoute = AdminPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchRoute = AdminMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipRoute = AdminMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTrailsRoute = AuthenticatedTrailsRouteImport.update({
  id: '/trails',
  path: '/trails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacesRoute = AuthenticatedPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListenRoute = AuthenticatedListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirclesRoute = AuthenticatedCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalkIndexRoute = AuthenticatedWalkIndexRouteImport.update({
  id: '/walk/',
  path: '/walk/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WCodeRecapRoute = WCodeRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => WCodeRoute,
} as any)
const AdminRadioIdRoute = AdminRadioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRadioRoute,
} as any)
const AdminPodcastsFeedIdRoute = AdminPodcastsFeedIdRouteImport.update({
  id: '/$feedId',
  path: '/$feedId',
  getParentRoute: () => AdminPodcastsRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AuthenticatedWalkNewRoute = AuthenticatedWalkNewRouteImport.update({
  id: '/walk/new',
  path: '/walk/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrailsIdRoute = AuthenticatedTrailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTrailsRoute,
} as any)
const AuthenticatedReadPostIdRoute = AuthenticatedReadPostIdRouteImport.update({
  id: '/read/$postId',
  path: '/read/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacesKeyRoute = AuthenticatedPlacesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AuthenticatedPlacesRoute,
} as any)
const AuthenticatedListenIdRoute = AuthenticatedListenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedListenRoute,
} as any)
const AuthenticatedGroupsSlugRoute = AuthenticatedGroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncPodcastFeedsRoute =
  ApiPublicHooksSyncPodcastFeedsRouteImport.update({
    id: '/api/public/hooks/sync-podcast-feeds',
    path: '/api/public/hooks/sync-podcast-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBlogFeedsRoute =
  ApiPublicHooksSyncBlogFeedsRouteImport.update({
    id: '/api/public/hooks/sync-blog-feeds',
    path: '/api/public/hooks/sync-blog-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedListenCollectionSlugRoute =
  AuthenticatedListenCollectionSlugRouteImport.update({
    id: '/collection/$slug',
    path: '/collection/$slug',
    getParentRoute: () => AuthenticatedListenRoute,
  } as any)
const ApiPublicWalkCodeStoryRoute = ApiPublicWalkCodeStoryRouteImport.update({
  id: '/api/public/walk/$code/story',
  path: '/api/public/walk/$code/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalkCodeRsvpRoute = ApiPublicWalkCodeRsvpRouteImport.update({
  id: '/api/public/walk/$code/rsvp',
  path: '/api/public/walk/$code/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalkCodeOgRoute = ApiPublicWalkCodeOgRouteImport.update({
  id: '/api/public/walk/$code/og',
  path: '/api/public/walk/$code/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalkCodeIcsRoute = ApiPublicWalkCodeIcsRouteImport.update({
  id: '/api/public/walk/$code/ics',
  path: '/api/public/walk/$code/ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/welcome': typeof WelcomeRoute
  '/circles': typeof AuthenticatedCirclesRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/listen': typeof AuthenticatedListenRouteWithChildren
  '/places': typeof AuthenticatedPlacesRouteWithChildren
  '/trails': typeof AuthenticatedTrailsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/podcasts': typeof AdminPodcastsRouteWithChildren
  '/admin/radio': typeof AdminRadioRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/shop/return': typeof ShopReturnRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$code': typeof WCodeRouteWithChildren
  '/groups/$slug': typeof AuthenticatedGroupsSlugRoute
  '/listen/$id': typeof AuthenticatedListenIdRoute
  '/places/$key': typeof AuthenticatedPlacesKeyRoute
  '/read/$postId': typeof AuthenticatedReadPostIdRoute
  '/trails/$id': typeof AuthenticatedTrailsIdRoute
  '/walk/new': typeof AuthenticatedWalkNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/podcasts/$feedId': typeof AdminPodcastsFeedIdRoute
  '/admin/radio/$id': typeof AdminRadioIdRoute
  '/w/$code/recap': typeof WCodeRecapRoute
  '/walk/': typeof AuthenticatedWalkIndexRoute
  '/listen/collection/$slug': typeof AuthenticatedListenCollectionSlugRoute
  '/api/public/hooks/sync-blog-feeds': typeof ApiPublicHooksSyncBlogFeedsRoute
  '/api/public/hooks/sync-podcast-feeds': typeof ApiPublicHooksSyncPodcastFeedsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/walk/$code/ics': typeof ApiPublicWalkCodeIcsRoute
  '/api/public/walk/$code/og': typeof ApiPublicWalkCodeOgRoute
  '/api/public/walk/$code/rsvp': typeof ApiPublicWalkCodeRsvpRoute
  '/api/public/walk/$code/story': typeof ApiPublicWalkCodeStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/welcome': typeof WelcomeRoute
  '/circles': typeof AuthenticatedCirclesRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/listen': typeof AuthenticatedListenRouteWithChildren
  '/places': typeof AuthenticatedPlacesRouteWithChildren
  '/trails': typeof AuthenticatedTrailsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/podcasts': typeof AdminPodcastsRouteWithChildren
  '/admin/radio': typeof AdminRadioRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/shop/return': typeof ShopReturnRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$code': typeof WCodeRouteWithChildren
  '/groups/$slug': typeof AuthenticatedGroupsSlugRoute
  '/listen/$id': typeof AuthenticatedListenIdRoute
  '/places/$key': typeof AuthenticatedPlacesKeyRoute
  '/read/$postId': typeof AuthenticatedReadPostIdRoute
  '/trails/$id': typeof AuthenticatedTrailsIdRoute
  '/walk/new': typeof AuthenticatedWalkNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/podcasts/$feedId': typeof AdminPodcastsFeedIdRoute
  '/admin/radio/$id': typeof AdminRadioIdRoute
  '/w/$code/recap': typeof WCodeRecapRoute
  '/walk': typeof AuthenticatedWalkIndexRoute
  '/listen/collection/$slug': typeof AuthenticatedListenCollectionSlugRoute
  '/api/public/hooks/sync-blog-feeds': typeof ApiPublicHooksSyncBlogFeedsRoute
  '/api/public/hooks/sync-podcast-feeds': typeof ApiPublicHooksSyncPodcastFeedsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/walk/$code/ics': typeof ApiPublicWalkCodeIcsRoute
  '/api/public/walk/$code/og': typeof ApiPublicWalkCodeOgRoute
  '/api/public/walk/$code/rsvp': typeof ApiPublicWalkCodeRsvpRoute
  '/api/public/walk/$code/story': typeof ApiPublicWalkCodeStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/circles': typeof AuthenticatedCirclesRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/listen': typeof AuthenticatedListenRouteWithChildren
  '/_authenticated/places': typeof AuthenticatedPlacesRouteWithChildren
  '/_authenticated/trails': typeof AuthenticatedTrailsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/podcasts': typeof AdminPodcastsRouteWithChildren
  '/admin/radio': typeof AdminRadioRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/shop/return': typeof ShopReturnRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$code': typeof WCodeRouteWithChildren
  '/_authenticated/groups/$slug': typeof AuthenticatedGroupsSlugRoute
  '/_authenticated/listen/$id': typeof AuthenticatedListenIdRoute
  '/_authenticated/places/$key': typeof AuthenticatedPlacesKeyRoute
  '/_authenticated/read/$postId': typeof AuthenticatedReadPostIdRoute
  '/_authenticated/trails/$id': typeof AuthenticatedTrailsIdRoute
  '/_authenticated/walk/new': typeof AuthenticatedWalkNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/podcasts/$feedId': typeof AdminPodcastsFeedIdRoute
  '/admin/radio/$id': typeof AdminRadioIdRoute
  '/w/$code/recap': typeof WCodeRecapRoute
  '/_authenticated/walk/': typeof AuthenticatedWalkIndexRoute
  '/_authenticated/listen/collection/$slug': typeof AuthenticatedListenCollectionSlugRoute
  '/api/public/hooks/sync-blog-feeds': typeof ApiPublicHooksSyncBlogFeedsRoute
  '/api/public/hooks/sync-podcast-feeds': typeof ApiPublicHooksSyncPodcastFeedsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/walk/$code/ics': typeof ApiPublicWalkCodeIcsRoute
  '/api/public/walk/$code/og': typeof ApiPublicWalkCodeOgRoute
  '/api/public/walk/$code/rsvp': typeof ApiPublicWalkCodeRsvpRoute
  '/api/public/walk/$code/story': typeof ApiPublicWalkCodeStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/events'
    | '/groups'
    | '/impact'
    | '/journal'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/transparency'
    | '/welcome'
    | '/circles'
    | '/discover'
    | '/listen'
    | '/places'
    | '/trails'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/blogs'
    | '/admin/collections'
    | '/admin/events'
    | '/admin/insights'
    | '/admin/membership'
    | '/admin/merch'
    | '/admin/podcasts'
    | '/admin/radio'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/users'
    | '/blog/$slug'
    | '/events/$slug'
    | '/g/$slug'
    | '/shop/return'
    | '/u/$username'
    | '/w/$code'
    | '/groups/$slug'
    | '/listen/$id'
    | '/places/$key'
    | '/read/$postId'
    | '/trails/$id'
    | '/walk/new'
    | '/admin/blog/$id'
    | '/admin/podcasts/$feedId'
    | '/admin/radio/$id'
    | '/w/$code/recap'
    | '/walk/'
    | '/listen/collection/$slug'
    | '/api/public/hooks/sync-blog-feeds'
    | '/api/public/hooks/sync-podcast-feeds'
    | '/api/public/payments/webhook'
    | '/api/public/walk/$code/ics'
    | '/api/public/walk/$code/og'
    | '/api/public/walk/$code/rsvp'
    | '/api/public/walk/$code/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/events'
    | '/groups'
    | '/impact'
    | '/journal'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/transparency'
    | '/welcome'
    | '/circles'
    | '/discover'
    | '/listen'
    | '/places'
    | '/trails'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/blogs'
    | '/admin/collections'
    | '/admin/events'
    | '/admin/insights'
    | '/admin/membership'
    | '/admin/merch'
    | '/admin/podcasts'
    | '/admin/radio'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/users'
    | '/blog/$slug'
    | '/events/$slug'
    | '/g/$slug'
    | '/shop/return'
    | '/u/$username'
    | '/w/$code'
    | '/groups/$slug'
    | '/listen/$id'
    | '/places/$key'
    | '/read/$postId'
    | '/trails/$id'
    | '/walk/new'
    | '/admin/blog/$id'
    | '/admin/podcasts/$feedId'
    | '/admin/radio/$id'
    | '/w/$code/recap'
    | '/walk'
    | '/listen/collection/$slug'
    | '/api/public/hooks/sync-blog-feeds'
    | '/api/public/hooks/sync-podcast-feeds'
    | '/api/public/payments/webhook'
    | '/api/public/walk/$code/ics'
    | '/api/public/walk/$code/og'
    | '/api/public/walk/$code/rsvp'
    | '/api/public/walk/$code/story'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/events'
    | '/groups'
    | '/impact'
    | '/journal'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/transparency'
    | '/welcome'
    | '/_authenticated/circles'
    | '/_authenticated/discover'
    | '/_authenticated/listen'
    | '/_authenticated/places'
    | '/_authenticated/trails'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/blogs'
    | '/admin/collections'
    | '/admin/events'
    | '/admin/insights'
    | '/admin/membership'
    | '/admin/merch'
    | '/admin/podcasts'
    | '/admin/radio'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/users'
    | '/blog/$slug'
    | '/events/$slug'
    | '/g/$slug'
    | '/shop/return'
    | '/u/$username'
    | '/w/$code'
    | '/_authenticated/groups/$slug'
    | '/_authenticated/listen/$id'
    | '/_authenticated/places/$key'
    | '/_authenticated/read/$postId'
    | '/_authenticated/trails/$id'
    | '/_authenticated/walk/new'
    | '/admin/blog/$id'
    | '/admin/podcasts/$feedId'
    | '/admin/radio/$id'
    | '/w/$code/recap'
    | '/_authenticated/walk/'
    | '/_authenticated/listen/collection/$slug'
    | '/api/public/hooks/sync-blog-feeds'
    | '/api/public/hooks/sync-podcast-feeds'
    | '/api/public/payments/webhook'
    | '/api/public/walk/$code/ics'
    | '/api/public/walk/$code/og'
    | '/api/public/walk/$code/rsvp'
    | '/api/public/walk/$code/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  ImpactRoute: typeof ImpactRoute
  JournalRoute: typeof JournalRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  WelcomeRoute: typeof WelcomeRoute
  GSlugRoute: typeof GSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  WCodeRoute: typeof WCodeRouteWithChildren
  ApiPublicHooksSyncBlogFeedsRoute: typeof ApiPublicHooksSyncBlogFeedsRoute
  ApiPublicHooksSyncPodcastFeedsRoute: typeof ApiPublicHooksSyncPodcastFeedsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWalkCodeIcsRoute: typeof ApiPublicWalkCodeIcsRoute
  ApiPublicWalkCodeOgRoute: typeof ApiPublicWalkCodeOgRoute
  ApiPublicWalkCodeRsvpRoute: typeof ApiPublicWalkCodeRsvpRoute
  ApiPublicWalkCodeStoryRoute: typeof ApiPublicWalkCodeStoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$code': {
      id: '/w/$code'
      path: '/w/$code'
      fullPath: '/w/$code'
      preLoaderRoute: typeof WCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/return': {
      id: '/shop/return'
      path: '/return'
      fullPath: '/shop/return'
      preLoaderRoute: typeof ShopReturnRouteImport
      parentRoute: typeof ShopRoute
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/radio': {
      id: '/admin/radio'
      path: '/radio'
      fullPath: '/admin/radio'
      preLoaderRoute: typeof AdminRadioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcasts': {
      id: '/admin/podcasts'
      path: '/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminPodcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merch': {
      id: '/admin/merch'
      path: '/merch'
      fullPath: '/admin/merch'
      preLoaderRoute: typeof AdminMerchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/membership': {
      id: '/admin/membership'
      path: '/membership'
      fullPath: '/admin/membership'
      preLoaderRoute: typeof AdminMembershipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/trails': {
      id: '/_authenticated/trails'
      path: '/trails'
      fullPath: '/trails'
      preLoaderRoute: typeof AuthenticatedTrailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places': {
      id: '/_authenticated/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthenticatedPlacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listen': {
      id: '/_authenticated/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AuthenticatedListenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles': {
      id: '/_authenticated/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AuthenticatedCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/walk/': {
      id: '/_authenticated/walk/'
      path: '/walk'
      fullPath: '/walk/'
      preLoaderRoute: typeof AuthenticatedWalkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/w/$code/recap': {
      id: '/w/$code/recap'
      path: '/recap'
      fullPath: '/w/$code/recap'
      preLoaderRoute: typeof WCodeRecapRouteImport
      parentRoute: typeof WCodeRoute
    }
    '/admin/radio/$id': {
      id: '/admin/radio/$id'
      path: '/$id'
      fullPath: '/admin/radio/$id'
      preLoaderRoute: typeof AdminRadioIdRouteImport
      parentRoute: typeof AdminRadioRoute
    }
    '/admin/podcasts/$feedId': {
      id: '/admin/podcasts/$feedId'
      path: '/$feedId'
      fullPath: '/admin/podcasts/$feedId'
      preLoaderRoute: typeof AdminPodcastsFeedIdRouteImport
      parentRoute: typeof AdminPodcastsRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/_authenticated/walk/new': {
      id: '/_authenticated/walk/new'
      path: '/walk/new'
      fullPath: '/walk/new'
      preLoaderRoute: typeof AuthenticatedWalkNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trails/$id': {
      id: '/_authenticated/trails/$id'
      path: '/$id'
      fullPath: '/trails/$id'
      preLoaderRoute: typeof AuthenticatedTrailsIdRouteImport
      parentRoute: typeof AuthenticatedTrailsRoute
    }
    '/_authenticated/read/$postId': {
      id: '/_authenticated/read/$postId'
      path: '/read/$postId'
      fullPath: '/read/$postId'
      preLoaderRoute: typeof AuthenticatedReadPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/$key': {
      id: '/_authenticated/places/$key'
      path: '/$key'
      fullPath: '/places/$key'
      preLoaderRoute: typeof AuthenticatedPlacesKeyRouteImport
      parentRoute: typeof AuthenticatedPlacesRoute
    }
    '/_authenticated/listen/$id': {
      id: '/_authenticated/listen/$id'
      path: '/$id'
      fullPath: '/listen/$id'
      preLoaderRoute: typeof AuthenticatedListenIdRouteImport
      parentRoute: typeof AuthenticatedListenRoute
    }
    '/_authenticated/groups/$slug': {
      id: '/_authenticated/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof AuthenticatedGroupsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-podcast-feeds': {
      id: '/api/public/hooks/sync-podcast-feeds'
      path: '/api/public/hooks/sync-podcast-feeds'
      fullPath: '/api/public/hooks/sync-podcast-feeds'
      preLoaderRoute: typeof ApiPublicHooksSyncPodcastFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-blog-feeds': {
      id: '/api/public/hooks/sync-blog-feeds'
      path: '/api/public/hooks/sync-blog-feeds'
      fullPath: '/api/public/hooks/sync-blog-feeds'
      preLoaderRoute: typeof ApiPublicHooksSyncBlogFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/listen/collection/$slug': {
      id: '/_authenticated/listen/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/listen/collection/$slug'
      preLoaderRoute: typeof AuthenticatedListenCollectionSlugRouteImport
      parentRoute: typeof AuthenticatedListenRoute
    }
    '/api/public/walk/$code/story': {
      id: '/api/public/walk/$code/story'
      path: '/api/public/walk/$code/story'
      fullPath: '/api/public/walk/$code/story'
      preLoaderRoute: typeof ApiPublicWalkCodeStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/walk/$code/rsvp': {
      id: '/api/public/walk/$code/rsvp'
      path: '/api/public/walk/$code/rsvp'
      fullPath: '/api/public/walk/$code/rsvp'
      preLoaderRoute: typeof ApiPublicWalkCodeRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/walk/$code/og': {
      id: '/api/public/walk/$code/og'
      path: '/api/public/walk/$code/og'
      fullPath: '/api/public/walk/$code/og'
      preLoaderRoute: typeof ApiPublicWalkCodeOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/walk/$code/ics': {
      id: '/api/public/walk/$code/ics'
      path: '/api/public/walk/$code/ics'
      fullPath: '/api/public/walk/$code/ics'
      preLoaderRoute: typeof ApiPublicWalkCodeIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedListenRouteChildren {
  AuthenticatedListenIdRoute: typeof AuthenticatedListenIdRoute
  AuthenticatedListenCollectionSlugRoute: typeof AuthenticatedListenCollectionSlugRoute
}

const AuthenticatedListenRouteChildren: AuthenticatedListenRouteChildren = {
  AuthenticatedListenIdRoute: AuthenticatedListenIdRoute,
  AuthenticatedListenCollectionSlugRoute:
    AuthenticatedListenCollectionSlugRoute,
}

const AuthenticatedListenRouteWithChildren =
  AuthenticatedListenRoute._addFileChildren(AuthenticatedListenRouteChildren)

interface AuthenticatedPlacesRouteChildren {
  AuthenticatedPlacesKeyRoute: typeof AuthenticatedPlacesKeyRoute
}

const AuthenticatedPlacesRouteChildren: AuthenticatedPlacesRouteChildren = {
  AuthenticatedPlacesKeyRoute: AuthenticatedPlacesKeyRoute,
}

const AuthenticatedPlacesRouteWithChildren =
  AuthenticatedPlacesRoute._addFileChildren(AuthenticatedPlacesRouteChildren)

interface AuthenticatedTrailsRouteChildren {
  AuthenticatedTrailsIdRoute: typeof AuthenticatedTrailsIdRoute
}

const AuthenticatedTrailsRouteChildren: AuthenticatedTrailsRouteChildren = {
  AuthenticatedTrailsIdRoute: AuthenticatedTrailsIdRoute,
}

const AuthenticatedTrailsRouteWithChildren =
  AuthenticatedTrailsRoute._addFileChildren(AuthenticatedTrailsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCirclesRoute: typeof AuthenticatedCirclesRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedListenRoute: typeof AuthenticatedListenRouteWithChildren
  AuthenticatedPlacesRoute: typeof AuthenticatedPlacesRouteWithChildren
  AuthenticatedTrailsRoute: typeof AuthenticatedTrailsRouteWithChildren
  AuthenticatedGroupsSlugRoute: typeof AuthenticatedGroupsSlugRoute
  AuthenticatedReadPostIdRoute: typeof AuthenticatedReadPostIdRoute
  AuthenticatedWalkNewRoute: typeof AuthenticatedWalkNewRoute
  AuthenticatedWalkIndexRoute: typeof AuthenticatedWalkIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCirclesRoute: AuthenticatedCirclesRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedListenRoute: AuthenticatedListenRouteWithChildren,
  AuthenticatedPlacesRoute: AuthenticatedPlacesRouteWithChildren,
  AuthenticatedTrailsRoute: AuthenticatedTrailsRouteWithChildren,
  AuthenticatedGroupsSlugRoute: AuthenticatedGroupsSlugRoute,
  AuthenticatedReadPostIdRoute: AuthenticatedReadPostIdRoute,
  AuthenticatedWalkNewRoute: AuthenticatedWalkNewRoute,
  AuthenticatedWalkIndexRoute: AuthenticatedWalkIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminPodcastsRouteChildren {
  AdminPodcastsFeedIdRoute: typeof AdminPodcastsFeedIdRoute
}

const AdminPodcastsRouteChildren: AdminPodcastsRouteChildren = {
  AdminPodcastsFeedIdRoute: AdminPodcastsFeedIdRoute,
}

const AdminPodcastsRouteWithChildren = AdminPodcastsRoute._addFileChildren(
  AdminPodcastsRouteChildren,
)

interface AdminRadioRouteChildren {
  AdminRadioIdRoute: typeof AdminRadioIdRoute
}

const AdminRadioRouteChildren: AdminRadioRouteChildren = {
  AdminRadioIdRoute: AdminRadioIdRoute,
}

const AdminRadioRouteWithChildren = AdminRadioRoute._addFileChildren(
  AdminRadioRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminMembershipRoute: typeof AdminMembershipRoute
  AdminMerchRoute: typeof AdminMerchRoute
  AdminPodcastsRoute: typeof AdminPodcastsRouteWithChildren
  AdminRadioRoute: typeof AdminRadioRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminMembershipRoute: AdminMembershipRoute,
  AdminMerchRoute: AdminMerchRoute,
  AdminPodcastsRoute: AdminPodcastsRouteWithChildren,
  AdminRadioRoute: AdminRadioRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ShopRouteChildren {
  ShopReturnRoute: typeof ShopReturnRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopReturnRoute: ShopReturnRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface WCodeRouteChildren {
  WCodeRecapRoute: typeof WCodeRecapRoute
}

const WCodeRouteChildren: WCodeRouteChildren = {
  WCodeRecapRoute: WCodeRecapRoute,
}

const WCodeRouteWithChildren = WCodeRoute._addFileChildren(WCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  GroupsRoute: GroupsRoute,
  ImpactRoute: ImpactRoute,
  JournalRoute: JournalRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  WelcomeRoute: WelcomeRoute,
  GSlugRoute: GSlugRoute,
  UUsernameRoute: UUsernameRoute,
  WCodeRoute: WCodeRouteWithChildren,
  ApiPublicHooksSyncBlogFeedsRoute: ApiPublicHooksSyncBlogFeedsRoute,
  ApiPublicHooksSyncPodcastFeedsRoute: ApiPublicHooksSyncPodcastFeedsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWalkCodeIcsRoute: ApiPublicWalkCodeIcsRoute,
  ApiPublicWalkCodeOgRoute: ApiPublicWalkCodeOgRoute,
  ApiPublicWalkCodeRsvpRoute: ApiPublicWalkCodeRsvpRoute,
  ApiPublicWalkCodeStoryRoute: ApiPublicWalkCodeStoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
