/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as WalkActiveIdRouteImport } from './routes/walk.active.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GroupsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const WalkActiveIdRoute = WalkActiveIdRouteImport.update({
  id: '/walk/active/$id',
  path: '/walk/active/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/journal': typeof JournalRoute
  '/profile': typeof ProfileRoute
  '/welcome': typeof WelcomeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/walk/active/$id': typeof WalkActiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/journal': typeof JournalRoute
  '/profile': typeof ProfileRoute
  '/welcome': typeof WelcomeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/walk/active/$id': typeof WalkActiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/journal': typeof JournalRoute
  '/profile': typeof ProfileRoute
  '/welcome': typeof WelcomeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/walk/active/$id': typeof WalkActiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/groups'
    | '/journal'
    | '/profile'
    | '/welcome'
    | '/events/$slug'
    | '/events/new'
    | '/groups/$slug'
    | '/walk/active/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/groups'
    | '/journal'
    | '/profile'
    | '/welcome'
    | '/events/$slug'
    | '/events/new'
    | '/groups/$slug'
    | '/walk/active/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/events'
    | '/groups'
    | '/journal'
    | '/profile'
    | '/welcome'
    | '/events/$slug'
    | '/events/new'
    | '/groups/$slug'
    | '/walk/active/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRouteWithChildren
  GroupsRoute: typeof GroupsRouteWithChildren
  JournalRoute: typeof JournalRoute
  ProfileRoute: typeof ProfileRoute
  WelcomeRoute: typeof WelcomeRoute
  WalkActiveIdRoute: typeof WalkActiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/walk/active/$id': {
      id: '/walk/active/$id'
      path: '/walk/active/$id'
      fullPath: '/walk/active/$id'
      preLoaderRoute: typeof WalkActiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsNewRoute: typeof EventsNewRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsNewRoute: EventsNewRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GroupsRouteChildren {
  GroupsSlugRoute: typeof GroupsSlugRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsSlugRoute: GroupsSlugRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRouteWithChildren,
  GroupsRoute: GroupsRouteWithChildren,
  JournalRoute: JournalRoute,
  ProfileRoute: ProfileRoute,
  WelcomeRoute: WelcomeRoute,
  WalkActiveIdRoute: WalkActiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
